- name: Setup Tomcat on Amazon Linux 2023
  hosts: all
  become: yes

  vars:
    tomcat_version: "10.1.48"
    tomcat_install_dir: "/opt/tomcat"

  tasks:
    - name: Install Java 17 (Amazon Corretto)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Create Tomcat install directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Rename extracted Tomcat directory
      command: mv {{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }} {{ tomcat_install_dir }}/tomcat
      args:
        removes: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Copy tomcat-users.xml
      template:
        src: tomcat-users.xml
        dest: "{{ tomcat_install_dir }}/tomcat/conf/tomcat-users.xml"
        owner: root
        group: root
        mode: '0644'

    - name: Replace context.xml
      template:
        src: context.xml
        dest: "{{ tomcat_install_dir }}/tomcat/webapps/manager/META-INF/context.xml"
        owner: root
        group: root
        mode: '0644'

    - name: Make Tomcat scripts executable
      file:
        path: "{{ tomcat_install_dir }}/tomcat/bin"
        mode: '0755'
        recurse: yes

    - name: Create systemd service file for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          Type=forking
          User=root
          Group=root
          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_HOME={{ tomcat_install_dir }}/tomcat"
          ExecStart={{ tomcat_install_dir }}/tomcat/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/tomcat/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat service
      service:
        name: tomcat
        state: started
        enabled: yes
